name: 'Unity Builds'
description: 'Runs unity builds and tests'
author: 'Nick Cipollo'
inputs:
  build_method:
    description: 'The static method to execute during the build.'
    default: ''
  license:
    description: 'Your unity license. Use secrets!'
    default: ''
  mode:
    description: 'The mode to run the action in. Use build or test.'
    default: 'test'
  password:
    description: 'Your unity password. Required to generate license. Use secrets!'
    default: ''
  projectPath:
    description: 'Your unity project path relative to the repository root.'
    default: ''
  serial:
    description: 'Your unity pro serial number. Required to generate pro license. Not required for unity personal. Use secrets!'
    default: ''
  username:
    description: 'Your unity user name. Required to generate license. Use secrets!'
    default: ''
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'tag'
  color: 'gray-dark'

