name: 'Unity Builds'
description: 'Runs unity builds and tests'
author: 'Nick Cipollo'
inputs:
  username:
    description: 'Your unity user name. Use secrets'
    default: ''
  password:
    description: 'Your unity password. Use secrets!'
    default: ''
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'tag'
  color: 'gray-dark'

